// ====== FIXED USER_SETUP.H CONFIGURATION ======

#define USER_SETUP_LOADED

// 1. USE THE COMPATIBLE ST7796 DRIVER INSTRUCTIONS FOR NV3007
#define ST7796_DRIVER

// 2. DEFINE THE BAR TYPE RESOLUTION MATCHING THE PANEL SPEC
#define TFT_WIDTH  142
#define TFT_HEIGHT 428

// 3. EXACT OFFSET CALIBRATIONS PREVENTING VERTICAL WHITE LINES
#define TFT_COLUMN_OFFSET 12
#define TFT_ROW_OFFSET    10
#define TFT_INVERSION_ON

// 4. CLEAN CONFLICT-FREE SPI0 PIN CONFIGURATION
#define TFT_MISO  -1
#define TFT_MOSI   3   // Screen SDA -> Pico GP3 (Pin 5)
#define TFT_SCLK   2   // Screen SCL -> Pico GP2 (Pin 4)
#define TFT_CS     5   // Screen CS  -> Pico GP5 (Pin 7)
#define TFT_DC     4   // Screen DC  -> Pico GP4 (Pin 6)
#define TFT_RST    6   // Screen RST -> Pico GP6 (Pin 9)

// 5. STABLE TIMING MARGINS FOR STABLE PIXEL LOADING
#define SPI_FREQUENCY  4000000
#define SPI_READ_FREQUENCY 2000000
