; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_speed = 921600
monitor_speed = 115200
upload_port = 10.20.20.47
upload_protocol = espota
upload_flags = --auth=123456
board_build.f_cpu = 160000000L
board_build.filesystem = littlefs
build_flags = -Teagle.flash.4m3m.ld
lib_deps = 
	SPI
	adafruit/RTClib@^2.1.1
	arduino-libraries/NTPClient@^3.2.1
	adafruit/Adafruit MCP23017 Arduino Library@1.3.0
