[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2
framework = arduino
board_build.core = earlephilhower
board_build.f_cpu = 250000000L

build_flags =
    -D DONT_USE_FEEDBACK_LED
    -D NO_LED_FEEDBACK_CODE
    -D kiss_fft_scalar=float
    -I lib/kissfft
    -O3
    -Wl,--gc-sections

lib_deps = 
    moononournation/GFX Library for Arduino@^1.6.7
    z3t0/IRremote @ ^4.4.1